
print("***Wellcome to the bad name generator!!***")
print("               *********                  ")
print("          *******************             ")

city=(input("What is the mane of the city you grow up in?: "))
print(" ")
cat_name=(input("What is the mane of your cat?: "))

print("               *********                  ")
print("          *******************             ")


print('your bad name is : ' +cat_name+city+"!")